#!/usr/bin/env osascript
on run argv
    tell application "iTerm2"
        tell current session of current window
            write text argv
        end tell
    end tell

    tell application "MacVim"
        activate
    end tell
end run
